include:
# Corne without dongle
  # Corne with nice!view display(with nice_view_custom module) 适用于带nice_view的Corne
  - board: nice_nano_v2
    shield: Corne_L Nice_view_config nice_view_custom
    snippet: studio-rpc-usb-uart
    artifact-name: Corne_left_nice_view
  - board: nice_nano_v2
    shield: Corne_R Nice_view_config nice_view_custom
    artifact-name: Corne_right_nice_view
  - board: nice_nano_v2
    shield: Corne_L Nice_view_config nice_view
    cmake-args: >-
      -DCONFIG_ZMK_STUDIO=n
      -DCONFIG_ZMK_RGB_UNDERGLOW=n
      -DCONFIG_WS2812_STRIP=n
      -DCONFIG_ZMK_DISPLAY=y
      -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=n
      -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
    artifact-name: Corne_left_display_test

  - board: nice_nano_v2
    shield: settings_reset